name: Benchmark
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Specifies the name of the benchmark'
        required: true
      ref:
        description: 'Specifies the ref (e.g. main or a commit sha) to benchmark'
        default: 'main'
        required: false
      cluster:
        description: 'Specifies which cluster to deploy the benchmark on'
        default: 'zeebe-cluster'
        required: false
      cluster-region:
        description: 'Specifies the cluster region. Needed to retrieve cluster credentials'
        default: europe-west1-b
        required: false
      benchmark-load:
        description: 'Specifies which benchmark components to deploy. `starter`, `timer` and `publisher` can be assigned with the rate at which they publish. Allows arbitary helm arguments, like --set starter.rate=100'
        required: false
  workflow_call:
    inputs:
      name:
        description: 'Specifies the name of the benchmark'
        type: string
        required: true
      ref:
        description: 'Specifies the ref (e.g. main or a commit sha) to benchmark'
        default: 'main'
        type: string
        required: false
      cluster:
        description: 'Specifies which cluster to deploy the benchmark on'
        default: 'zeebe-cluster'
        type: string
        required: false
      cluster-region:
        description: 'Specifies the cluster region. Needed to retrieve cluster credentials'
        default: europe-west1-b
        type: string
        required: false
      benchmark-load:
        description: 'Specifies which benchmark components to deploy. `starter`, `timer` and `publisher` can be assigned with the rate at which they publish. Allows arbitary helm arguments, like --set starter.rate=100'
        type: string
        required: false
jobs:
  build-zeebe-image:
    name: Build zeebe image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      image-tag: ${{ steps.image-tag.outputs.image-tag }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - name: Get image tag
        id: image-tag
        run: |
          echo "image-tag=${{ inputs.name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup BuildKit
        uses: docker/setup-buildx-action@v2
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: gcr.io/zeebe-io/zeebe:${{ steps.image-tag.outputs.image-tag }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: DIST=build
          target: app
  deploy-benchmark-cluster:
    name: Deploy benchmark cluster
    needs:
      - build-zeebe-image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: ${{ inputs.cluster }}
          location: ${{ inputs.cluster-region }}
      - name: Add camunda helm repo
        run: |
          helm repo add zeebe-benchmark https://zeebe-io.github.io/benchmark-helm
          helm repo update
      - name: Helm install
        run: >
          helm upgrade --install ${{ inputs.name }} zeebe-benchmark/zeebe-benchmark
          --namespace ${{ inputs.name }}
          --create-namespace
          --set camunda-platform.zeebe.image.repository=gcr.io/zeebe-io/zeebe
          --set camunda-platform.zeebe.image.tag=${{ needs.build-zeebe-image.outputs.image-tag }}
          --set camunda-platform.zeebe-gateway.image.repository=gcr.io/zeebe-io/zeebe
          --set camunda-platform.zeebe-gateway.image.tag=${{ needs.build-zeebe-image.outputs.image-tag }}
          ${{ inputs.benchmark-load }}
